### ISSUE TITLE
Microsoft OneDrive (OneDrive Business) Cloud Support

### ISSUE THREAD

**Issue by mmcguill** [mmcguill/StrongBox#1]

**Comment by Ben-Voris** [comment]
I now have a password safe that I must store on OneDrive. 
My workaround is to tap on the '.psafe3' file in the OneDrive app, which brings up an info screen. Then I tap on the file name, and use the *Copy to Strongbox* action.  Unfortunately, the Strongbox app presents this as two safes, both with the same name. There is only one file on iCloud.

**Comment by mmcguill** [comment]
OneDrive Personal implemented now, but OneDrive Business is a separate integration unfortunately, so I'll leave this open. Hopefully it's not too much different from the Personal integration.

**Comment by mmcguill** [comment]
Just an update. OneDrive for Business is quite a different integration. Unfortunately the library I use to integrate with OneDrive is also broken for the Business mode. I've asked someone to take a look, but again, unfortunately, I have a feeling the library is not being very actively maintained. I may have to try to fix the issue myself. 

https://github.com/OneDrive/onedrive-sdk-ios/issues/202

On top of this, it is hard to determine if Microsoft require an ongoing subscription to Azure to allow my app to integrate against their OneDrive for business option. Struggling to get a definitive answer on this at the moment. If there is a subscription required, I would need to consider adding an extra charge in Strongbox to cover this cost... Not great news unfortunately, and OneDrive is proving a pretty difficult integration.

**Comment by mmcguill** [comment]
I believe I've solved this problem now, and with release 1.17.0 (available in the App Store now) you should be able to login using either OneDrive Personal or OneDrive business credentials. 

I had to modify the OneDrive library source to get this working. I'd appreciate any feedback you have!

Also, I've been in touch with Microsoft, they are pretty sure that I don't need a paid Azure subscription just to have an App Registration (which is required of ODfB integration), so fingers crossed this is true.

I'll leave this issue open until I get some confirmations other than my own logins.

-Mark

**Comment by mmcguill** [comment]
This appears to be complete now.

**Comment by pschwien82** [comment]
Hi,
I had time to try it out now and noticed that during the setup process, Strongbox requests permissions to a very long list of items, including sensitive things like "Read all emails". I assume you used a wildcard for testing this but now that it is working, can you reduce the needed permissions to a minimum? As a security tool, this would otherwise undermine the trustworthyness a bit I believe.

Thanks so much for working on this feature though!

Here a screenshot of the first (out of 5 or 6 pages of requested permissions).
![file-5](https://user-images.githubusercontent.com/38443094/49400321-cc04f780-f6f8-11e8-89c3-a6a4daf460d8.jpeg)

**Comment by mmcguill** [comment]
Thanks for that George, you were indeed correct, I had opened these permissions up while developing and forgot to narrow them down. Should be much better now, this is what I think is the minimum needed for Strongbox to function correctly:

![img_3775](https://user-images.githubusercontent.com/344791/49444219-5f582e80-f7c6-11e8-89fd-493db959ca41.jpg)

**Comment by Ben-Voris** [comment]
I have been using a workaround (see below) to access a safe stored on OneDrive Business. For some reason, the safe added this way was not receiving updates and I could not disable the cache (the switch appeared but was dimmed).  I tried adding the safe directly on OneDrive and that works. So, I think this issue should be closed.

For future reference, the that Mark sent to me was:
1. Tap the '+' button in Strongbox
2. Select 'Add Existing Safe'
3. Select 'Files'
4. Navigate to your OneDrive safe
5. Tap on your file
6. Strongbox will ask if you would like to 'Edit in Place' or 'Copy'
7. Select 'Edit in Place'
8. This should add your OneDrive safe with a 'Green' file icon

Haven't a clue why this stopped working, but since the direct method works now, I'm happy.
