### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by pdp2015** [mmcguill/StrongBox#10]
Build has failed with this message:

'ISMessages/ISMessages.h' file not found

ISMessages/ISMessages.h fine not found
SafeDetailsView.m

**Comment by mmcguill** [comment]
Hi @pdp2015, what are you trying to do exactly, and how are you building this?

**Comment by pdp2015** [comment]
Using xcode it fails to build

**Comment by pdp2015** [comment]
Ran pod install then opened the xcode workspace then it fails unless im missing something?

**Comment by mmcguill** [comment]
Do you mind me asking what you are doing with the code? It's here for primarily so that people can inspect the code for security reasons. If you want to use the app, you can download it on the app store, there's always a running version there. I can't guarantee the repository will always build, I don't have the resources to fix users build issues. Do you want to contribute to the project?

**Comment by pdp2015** [comment]
Was purely just having a look hownits put together thats all

**Comment by mmcguill** [comment]
Thanks for your interest. I'd ask that you not open any build issues here unless you're actively contributing to the project in some form. All the best.
-Mark
