### ISSUE TITLE
No Issues Just a Question about Sorting

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#139]
I like the latest round of UI layout changes.  I also like that you implemented robust sorting functionality at the view level instead of the older method which impacted the database structure and required a database save each time.  I noticed that the older method is still available if the "None (Custom Order)" is selected.  What's the use case for that decision?  It seems like the older method could be deprecated in favor of the newer, better method but that's just my opinion.

**Comment by mmcguill** [comment]
Yes, I left that functionality in there, maybe people who like to have their own order might want to sort a folder alphabetically and then re-arrange from there. I'm not sure anyone will use it at all to be honest, but the feature is there, and I saw no point in removing it. It does ask/prompt you before doing it, so that you know it will effect the underlying database, as opposed to the view based sort.

**Comment by shad0whawk** [comment]
Actually that makes sense because it provides an easy way to quickly sort the database, and alphabetically is probably the most common method. I think you should leave it in going forward.

**Comment by mmcguill** [comment]
Yeah, just thought there was little point removing functionality, maybe someone will find it useful. Ok to close this issue?

**Comment by shad0whawk** [comment]
Yes
