### ISSUE TITLE
iOS Feature Request:  Option to Switch View from Grouped Folder Structure to Flat View

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#140]
It would be useful--but not critical--to have the ability to switch the folder/entry view from a grouped folder structure as in the current implementation to a flat view. In KeePass this is done by turning off the grouping option.  This would expand the sorting capabilities because then we would be able to sort the view across all entries instead of just the subfolder.  This should only impact the view not the database structure itself.

**Comment by mmcguill** [comment]
Interesting idea yes, I think this is very doable. 

You can currently achieve something similar by initializing Search with no filter, so when you first activate search you will see a list of all entries. I presume this is what you mean?

I think this could be combined with #132 so that in the View Preferences menu/popup screen, you'd have an option: 

"View As" -> 

[Hierarchy (Default and current standard)]
[List (Flat/Search like view I believe you're talking about)]
[TOTP (Only TOTP entries with enlarged Font containing the TOTP code, similar to Google Authenticator)]

How's that sound?

**Comment by shad0whawk** [comment]
I like that idea. It gives the user a few options depending on how they use the database.

**Comment by mmcguill** [comment]
This is available for you with 1.32.1. Interested to hear your feedback.

**Comment by shad0whawk** [comment]
I like the new options for both TOTP and flat view. It’s very easy to switch between the views. In flat view, it’s also easy and usefu to sort the entries by the desired attribute. This allows me to easily see the last entries I’ve modified. Thank you!

**Comment by shad0whawk** [comment]
I like how the database View Preferences have been separated into their own configuration menu. Is it possible to configure the program so that the view preferences are—or can be optionally—specific to the database? The current implementation appears to enforce them globally across all databases. This would be nice so I can have one database setup for TOTP with one set of view options, and another database setup as hierarchy with a different set of view options.

**Comment by shad0whawk** [comment]
Or keep the global options but have an optional override at the database level.

**Comment by mmcguill** [comment]
So, actually the "View As" preference is per database, so that should work for you already, but I think the other preferences could be moved to be per database rather than global, might be useful for people... I'll create an issue for it now.

**Comment by mmcguill** [comment]
Ok to close this one @shad0whawk ?

**Comment by shad0whawk** [comment]
Yep
