### ISSUE TITLE
Split-view “jumps” when typing data

### ISSUE THREAD

**Issue by hajosc** [mmcguill/Strongbox#152]
In split view, when typing data like a password, the view “jumps” up and down by about 1/2 line on every keystroke. This only happens if the view is scrolled all the way to the bottom.

**Comment by shad0whawk** [comment]
I have a similar issue on my iPhone with the database view in TOTP mode. If you scroll up and down and then stop where the header for a partial line is shown, then the screen jumps up and down continuously. I’ll send a screen recording to your support mail box.

**Comment by mmcguill** [comment]
Thanks for the bug report guys

**Comment by Slummi** [comment]
I have a similar issue in all database views (e.g. flat hierarchy). The list and the scroll bar "jump" always up and down when you are scrolling. So scrolling through a long list of entries isn't really smooth.

**Comment by Slummi** [comment]
Hi @mmcguill,

I recoreded a video of this jumping effect. Maybe it helps to identify it's cause.
[Test Scrolling.zip](https://github.com/mmcguill/Strongbox/files/3350316/Test.Scrolling.zip)

This effect seems not to occur in all databases and all folder views. So far, I couldn't find any patterns, when this effect occurs and when it does not.

Due to privacy reasons all titles and user names are identical.

**Comment by Slummi** [comment]
With 1.35.0 scrolling is much smoother than before. But it's still a little bit jerking.
I didn't recognize that this effect only occurs, if there is a TOTP code in the visible area of the list. If you are in an area without any TOTP code, scrolling is very fluent.

But I'm wondering why it is only jerking, if you scroll down and not if you scroll up.

**Comment by mmcguill** [comment]
Yes, ok, good to hear there is some improvement... The jerking is down to the TOTP code refresh, which I've tried to minimize. It's a difficult one to get exactly perfect, but there's possibly one more thing I can try to improve things. I'll keep this open for now. I hope you can live with it as is for the moment.

**Comment by Slummi** [comment]
Yes, I can live with it as it is for the moment. But do you have an explanation why this happens only when scrolling down, but not when scrolling up? The code refrehsing is independent of the scrolling direction, isn't it?

By the way, when you are in OTTP view at the end of the list, the list is bouncing up and down all the time.

**Comment by shad0whawk** [comment]
In general, the behavior is much improved for me in version 1.35.0 on my iPhone XS running iOS 12.3.2. I have noticed a new issue on my iPhone 8 running iOS 13 beta 3. If I open the database in TOTP List view and scroll down my list of TOTP entries to the bottom, the view slowly bounces its way back to the top one bounce per second. It’s very consistent but I’m not sure if it’s due to iOS 13 or not. Just FYI...

**Comment by mmcguill** [comment]
@hajosc I can't explain the up vs down motion, I'd imagine it's an artefact of how UITableView manages scrolling internally. The solution hopefully will be to manage TOTP UI Updates at the Cell level rather than at the Table level. Keep an eye out for that in the coming couple of releases.

**Comment by Slummi** [comment]
There’s no longer any bouncing or jerking in 1.35.2. Well done!

**Comment by mmcguill** [comment]
That's awesome to hear! Thanks @Slummi - I'll close this one out

**Comment by shad0whawk** [comment]
The iOS 13 issue I mentioned previously no longer exists either. Nice job!
