### ISSUE TITLE
Files based Database (Edit-in-place) Crash after external update

### ISSUE THREAD

**Issue by shad0whawk** [mmcguill/Strongbox#22]
Thanks for expanding this application to include Keepass.  I really enjoy the aesthetics, functionality, and ease of use it provides while allowing me to access my data on my iOS device.  

Either I found and issue or I don't understand the expected behavior for my use case.

I have a Keepass database replicated to iCloud that I've opened/linked to in Strongbox using Edit in Place mode on my iPhone running iOS 12.1.2.  This is a copy of the master database so it is periodically overwritten with an updated version using a syncing software.  I can initially link the database and open it without any issues until the copy in iCloud is updated with a newer version of the same database--same master key, new timestamp--and then Strongbox crashes completely when I try to authenticate using Face ID.  I've opened the Files application and made sure the database is download to my device.  The only fix is to remove the linked database and add it again from iCloud.  I'd expect the application to open the updated database without crashing if all parameters of the database are still the same but that is not the case.

**Comment by shad0whawk** [comment]
Thanks for the quick response. I’ll give it try later today and see if your suggested method works. I’ll keep you posted.

**Comment by mmcguill** [comment]
Hi @shad0whawk, I'm afraid this one is a little difficult to handle correctly. Apple doesn't handle this stale bookmark situation well, and the best advice appears to be to re-add/create the bookmark manually. You can read a little more here: https://stackoverflow.com/questions/23954662/what-is-the-correct-way-to-handle-stale-nsurl-bookmarks

I've made a change in Strongbox which will go out with the next release, so that it at least won't crash. If you can get your iCloud working it would be the best way out of the situation for sure.

**Comment by shad0whawk** [comment]
I understand and I appreciate you looking at it. I’ll figure out the best approach as far as iCloud goes. Everything works great with OneDrive so far so that’s probably the best route to go.

**Comment by mmcguill** [comment]
Ok, glad to hear it, I'll close this for the moment at least.
