### ISSUE TITLE
Question: Handling of convenience pins

### ISSUE THREAD

**Issue by eike-f** [mmcguill/Strongbox#34]
I looked through the code and would just like a clarification because I don't speak objective C and also am not very fluent in regular c.

Are the convenience pins also stored in the keychain and hence encrypted?
I would very much like that.

**Comment by mmcguill** [comment]
Hi @eike-f, Yeah, so the Convenience and Duress pins are stored in the Keychain. The App Level Privacy lock screen (which I've had to remove in the latest release due to various bugs and interferences with other dialogs) did not use the Keychain (though this could have been changed relatively straightforwardly).
