### ISSUE TITLE
Corrupted attachments in KDBX entry history

### ISSUE THREAD

**Issue by anmipo** [mmcguill/Strongbox#74]
As you know, KDBX databases keep a history of changes for each entry (Edit Entry - History tab in KeePass2). These "historical" entries also include entry attachments. For instance, if one removes an attachment from an entry, that attachment would normally remain available in the "historical" entry.

This works in KeePass2 and KeePassXC. However, after the database is saved by Strongbox, historical attachments become zero-sized (missing from DB's binary pool, to be specific). 

Not too critical, but surely unpleasant if you happen to need a scan of your previous passport...

P.S. Discovered by KeePassium, which complained about this during cross-app testing :)

**Comment by mmcguill** [comment]
Hi @anmipo , thanks for the bug report, appreciate it. Sounds like an oversight. I'll look into it as soon as I can and get back to you here...

**Comment by mmcguill** [comment]
Good spot here @anmipo and thanks for the report. I've patched this up now, and should be fixed in 1.24.0 (iOS) and 1.5.3 (macOS). 

Happy to hear about any other bugs you find in this cross-app testing! Please let me know.

Will leave this open for a short while in case there are issues with the release...

Cheers,
-Mark

**Comment by anmipo** [comment]
Well done, Mark! 
I will surely update you if anything else comes up.

Cheers,
Andrei

**Comment by mmcguill** [comment]
Think we're good here...
